version: '3.9'

services:

  node-app:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongo_db:27017/taskmanagementsystem
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
      NODE_ENV: test
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    ports:
      - 2717
    volumes: 
      - mongo_db:/data/db
    depends_on:
      - volumes

volumes:
  mongo_db: {}